error_list = {
    "Escape" : ["Escape ", " inexistente."],
    "FNoDeclarada" : ["La funcion ", " no fue declarada."],
    "NoFuncion" : [" no es una funcion."],
    "TipoInexistente" : ["No existe el tipo "],
    "NoRecord" : ["El tipo ", " no es un record."],
    "TiposArgumentos" : ["No coinciden los tipos de los argumentos de ", "."],
    "TipoCampo" : ["Tipo incorrecto del campo ", "."],
    "VNoDeclarada" : ["La variable ", " no fue declarada."],
    "TNoDeclarado" : ["El tipo ", " no fue declarado."],
    "NoExiste" : [" **no existe!!!"],
    "Completar" : ["COMPLETAR."],
    "CantidadArgumentos" : ["No coinciden la cantidad de argumentos."],
    "OperandosDistintos" : ["Los tipos de los operandos son diferentes."],
    "TiposNoComparables" : ["Los tipos no son comparables."],
    "TiposNoOperables" : ["Los tipos no son operables."],
    "CamposDistintos" : ["No coinciden los campos."],
    "SoloLectura" : ["Intento de asignacion a variable de solo lectura."],
    "AsignacionIncorrecta" : ["El tipo de la variable no coincide con el de la expresion."],
    "IndiceIncorrecto" : ["El tipo del indice debe ser int."],
    "IfDiferentes" : ["Las ramas del if tienen diferentes tipos."],
    "CondicionIncorrecta" : ["El tipo de la condicion debe ser int."],
    "CuerpoIncorrecto" : ["El tipo del cuerpo debe ser unit."],
    "ExtremosIncorrectos" : ["Los tipos de los extremos deben ser int."],
    "TamanoIncorrecto" : ["El tipo del tamaño debe ser int."],
    "InitIncorrecto" : ["No coincide el tipo del valor inicial con el de la estructura."],
    "AsignacionNil" : ["No se puede asignar Nil a una variable sin especificar el tipo."],
    "ErrorInterno" : ["Error interno."],
    "NoVariable" : ["No se puede asignar nada a una funcion."],
    "TipoCiclico" : ["Declaracion de tipos mutuamente recursivos."],
    "NoArray" : ["La variable no es un array."],
    "CicloInterrumpido" : ["Batch de declaracion interrumpido"],
    "CampoInexistente" : ["No existe ese campo en el registro."],
    "RetornoIncorrecto" : ["Alguna funcion del batch no devolvio lo que se esperaba."],
    "OK" : ["bien!"]
}
